Update readme
blindnet-io/sdk-javascript-client pull request #7
Opened 2022-06-17 16:21 UTC by filipblnt

Draft PR for finishing the README.

2022-06-20 23:34 UTC, noelmace commented
I'm using this PR as an example for https://github.com/blindnet-io/openness-framework/pull/33.

As I'm now a co-author, it LGTM, obviously :smile: So I'm making @m4rk055 the reviewer and assignee.

Please keep this PR review about its specificities only, and give any feedback about the template itself in https://github.com/blindnet-io/openness-framework/pull/33.

2022-06-20 23:34 UTC, noelmace approved these changes

2022-06-21 08:26 UTC, m4rk055 requested changes

2022-06-21 08:26 UTC, m4rk055 commented on README.md
> +  <strong>JavaScript <a href="https://blindnet.dev/docs/extra/glossary/#client-side-sdk">client-side SDK</a> for e2e encryption and users management.</strong>
Structure of the docs changed a bit. Remove `/extra` from every _blindnet.dev_ link in the README

2022-06-21 08:26 UTC, m4rk055 commented on README.md
> +:rocket: Check out our [Quick Start Guide](http://localhost:3000/docs/quickstart) to get started in a snap.
```suggestion
:rocket: Check out our [Quick Start Guide](https://blindnet.dev/docs/quickstart) to get started in a snap.
```

2022-06-21 08:26 UTC, m4rk055 commented on README.md
> +The blindnet devkit sdk-javascript-client is available under [MIT](license) (and [here](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) is wh
```suggestion
The blindnet devkit sdk-javascript-client is available under [MIT][license] (and [here](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0001-oss-license.md) is why).
```

2022-06-21 09:42 UTC, noelmace commented on README.md
> +:rocket: Check out our [Quick Start Guide](http://localhost:3000/docs/quickstart) to get started in a snap.
oupsy :sweat_smile:

2022-06-22 11:43 UTC, merged